/**
 * Part 2 of every prompt: the rules that make an AI's page work well in this
 * editor (one file, real text in real elements, plain CSS on classes, scripts
 * that only enhance). Keep in step with the parser (editor/model/parse) and
 * the editor frame (scripts run sandboxed; screen sizes 1024px / 640px).
 */
export const PROMPT_RULES = `PART 2 — OUTPUT RULES (keep these exactly)

The page will be pasted into a visual editor where people change it by clicking: they edit text, swap pictures, change colors and spacing, reorder sections and adjust the tablet and phone layouts. Follow every rule below so each part stays easy to edit.

1. ANSWER FORMAT
- Reply with exactly ONE html code block holding the complete page, and nothing else: no explanations, notes, alternatives or setup steps before or after it.
- Start with <!doctype html> and include <html lang="…">, <head> and <body>. Use the language from Part 1 for lang and for all copy.

2. ONE SELF-CONTAINED FILE
- <head>: <meta charset="utf-8">, <meta name="viewport" content="width=device-width, initial-scale=1">, a descriptive <title>, a short meta description, the Google Fonts <link> tags (with preconnect), then ONE <style> element with all the CSS.
- End of <body>: ONE <script> element with all the JavaScript.
- No other files: no external CSS or JS, no CSS or JS frameworks (no Tailwind, Bootstrap, jQuery, React, Vue, GSAP), no build steps, no imports, no web components, no iframes, no <canvas> for content.

3. PAGE STRUCTURE
- Body order: <header> (logo + nav), <main> with one <section> per part of the page, <footer>.
- Every <section> gets an id (used by the nav links, e.g. href="#menu") and a clear class (class="section menu").
- Use short, human class names that say what a thing is: .hero, .card, .price, .btn, .btn-outline, .gallery, .faq. Reuse the same class for repeated items (every card is .card) so one change can restyle them all.
- Wrap section content in <div class="container"> for the page width. Keep nesting shallow: no extra wrapper divs that do nothing.
- Repeated items (cards, team members, menu items, reviews) are real siblings in the HTML, all written out — never generated by JavaScript from an array.

4. TEXT
- Every visible word is real text inside a real element: headings in h1–h6 (exactly one h1, in the hero), paragraphs in <p>, lists in <ul>/<ol> with <li>, links in <a>, actions in <button>.
- Never put visible text in CSS (content: "…"), in images, in SVG <text>, in data attributes or in JavaScript strings that get written into the page.
- A heading or paragraph holds plain text, optionally with <strong>, <em>, <a> or <span class="…"> for a highlighted word. Do not split a sentence across many styled spans or elements.
- Write real, specific, friendly copy for the business or person in Part 1 — no lorem ipsum, no "Your text here". Use the names, prices, dates and details given; invent believable ones only where Part 1 gives none.
- Buttons that go somewhere are <a class="btn" href="…">; use # links to sections, tel:, mailto: or a full https:// address.

5. PICTURES AND ICONS
- Pictures are <img> tags with a full https:// address, width and height attributes, and a helpful alt text. Use Unsplash photos that fit the subject: https://images.unsplash.com/photo-…?auto=format&fit=crop&w=1200&q=80 (w=600 for cards, w=1600 for full-width heroes).
- Never use base64 images, local file names or CSS background-image for photos people may want to change (a decorative gradient background is fine).
- Icons: small inline <svg> with viewBox and currentColor, or an emoji in a <span class="icon">.

6. CSS
- Put colors, fonts, radius and spacing in custom properties on :root (for example --color-primary, --color-text, --color-bg, --font-heading, --font-body, --radius, --space) and use them everywhere.
- Style with classes. No inline style="" attributes, no styling by id, no !important, no html { font-size } changes.
- Sizes in px, rem, %, fr or clamp(); body text at least 16px; line-height around 1.5–1.7.
- Layout with flexbox and grid; images get max-width: 100% and height: auto (object-fit: cover inside fixed frames).
- Make it look great on every screen, desktop first, with exactly these two breakpoints: @media (max-width: 1024px) for tablets and @media (max-width: 640px) for phones. On phones, grids become one column, the nav collapses into a menu button, and nothing scrolls sideways.
- Only the header may be sticky. Avoid position: fixed overlays, 100vh sections and fixed pixel heights on text boxes (use min-height and padding).
- Animations are gentle and short, and turn off under @media (prefers-reduced-motion: reduce).

7. JAVASCRIPT
- Plain JavaScript only, and only to enhance what is already in the HTML: the mobile menu toggle, tabs, sliders, counters, countdowns, scroll reveal, a "copied!" note.
- The page must be complete and readable with JavaScript off: all content is visible in the HTML from the start. For reveal-on-scroll, add the hidden starting state from JavaScript (e.g. add a "js" class to <html>, then style .js .reveal), never in plain CSS.
- Change classes and attributes, not content: no innerHTML/insertAdjacentHTML templates, no document.write, no creating sections or cards from data. A countdown or counter may update the text of an element that already shows a sensible value in the HTML.
- Tabs: <button> tabs plus panels, where the panels that start closed have the hidden attribute. FAQs: <details> with <summary>, no JavaScript needed.
- No alert(), confirm() or prompt(), no pop-ups on load, no localStorage, no network requests, no tracking or third-party widgets.
- Forms (contact, RSVP, sign-up): real <label> for every field and action="#"; on submit, prevent the default and show a short thank-you message that is already in the HTML (hidden attribute until then).

8. DESIGN — MAKE IT EYE-CATCHING
- Start from one clear visual idea that fits the subject (its mood, palette, type pairing and a recurring motif) and carry it through every section. It must not look like a generic template or a plain list of boxes.
- Hero: the most striking part of the page. A big, expressive headline (font-size with clamp(), roughly 44–96px on desktop), a strong photo or rich layered background (gradients, soft shapes, a gentle overlay so text stays readable), a short supporting line and one standout button.
- Color: one dominant color, one bold accent and a few neutrals, all as :root variables. Use them with confidence: alternate light and dark (or tinted) sections for rhythm, use the accent for buttons, highlights and key numbers.
- Typography: a characterful display font for headings and a clean, readable body font. Small uppercase labels with letter-spacing above headings, large numbers for stats and prices, comfortable line lengths (about 60–75 characters).
- Depth and detail: soft layered shadows, rounded or distinctive card shapes, thin dividers, badges and chips, subtle texture or gradient glows, decorative shapes made with CSS pseudo-elements or inline SVG (decoration only — never text).
- Layout variety: mix layouts (split screen, asymmetric grids, overlapping photo and card, a bento grid, one full-width image band) instead of repeating the same centred stack; generous white space between sections.
- Motion with taste: hover lifts and color shifts on cards and buttons, a gentle zoom on photos, scroll-reveal and count-up numbers as enhancements, all short (150–600ms) and switched off under prefers-reduced-motion.
- Photos: high-quality, on-topic and consistent in mood and color; crop them with object-fit and frame them well (rounded, arched or with an offset shape behind).

9. QUALITY
- Strong, readable color contrast; visible focus styles on links and buttons; alt text on every picture; aria-label on icon-only buttons.
- Consistent spacing rhythm between sections, a clear visual hierarchy and one obvious main action.
- The footer has the name, short contact details, links and © with the current year.

10. BEFORE YOU ANSWER, CHECK
- One html code block, nothing outside it. One <style> in <head>, one <script> at the end of <body>.
- Every section has an id and a class; repeated items share a class; all text is real HTML text.
- It works at 1440px, 1024px, 768px, 390px and 360px wide, with and without JavaScript.
- It would stand out next to a site from a top design studio: a memorable hero, a confident palette and real visual variety from section to section.`
